### ISSUE TITLE
[TRI-689] Login through magic link not working in Safari when running on localhost:3030

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#186]
Safari version: Version 16.4.1 (17615.1.26.101.10, 17615)

To recreate, make sure you DON'T have the `RESEND_API_KEY` env var set, so the magic link is printed to the terminal instead of actually sent as an email (I can't recreate the problem when the magic link is sent through the email).

After navigating to the magic link (in Safari) you will get redirected back to the magic link page, instead of into the dashboard.

I'm thinking this might have something to do with the the cookie session storage (which you can find here: https://github.com/triggerdotdev/trigger.dev/blob/bca0df2692a9255d79a3858e8bb091cdfa883632/apps/webapp/app/services/sessionStorage.server.ts) but I'm not exactly sure what is causing it

<sub>[TRI-689](https://linear.app/triggerdotdev/issue/TRI-689/login-through-magic-link-not-working-in-safari-when-running-on)</sub>

**Comment by imrishabh18** [comment]
Hey @ericallam,  I have tried couple of times to recreate the issue, but the magic link in my terminal is redirecting it to the Dashboard. Can you share some more steps please or am I missing something?

P.S. - I am a beginner to open source contributions, would love to help and contribute.

**Comment by SSHari** [comment]
@ericallam It looks like this might be the result of the cookie being sent with the [secure flag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie). What's odd is that MDN mentions that this shouldn't be a problem for `localhost`, but it might be a bug with Safari.

I changed the `NODE_ENV` in the `start` script as follows so it runs in development mode:
<img width="1197" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/11434879/26941109-e469-4385-900a-de4615ec94ae">

Changing the environment toggles the secure flag here:
<img width="967" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/11434879/4e943d82-4a11-410f-8f5f-7f6c5b5141b4">

Running the app this way removes the `Secure` flag from the cookies that are returned from the server. I was able to get things working after making this change.

Here's an example of the before/after of a returned cookie:

### Before
<img width="758" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/11434879/afe183e0-4356-49bc-bfd5-fc37cbfad812">

### After
<img width="708" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/11434879/fda0358a-290f-4724-85ff-800689489931">

I guess the question is are you only seeing this locally, or are you also experiencing this in a deployed version of the application?

**Comment by ericallam** [comment]
Oh interesting, I actually think we should probably remove setting the NODE_ENV like that so we can run `start` with either NODE_ENV=production and NODE_ENV=development, although I wonder if the NODE_ENV=production line in the Dockerfile will override that.

**Comment by ericallam** [comment]
Just to note, you can build the Docker image locally using the following command:

```sh
docker build -f ./docker/Dockerfile -t <tag name here> .
```

**Comment by ericallam** [comment]
@imrishabh18 have you seen the above comments?

**Comment by rishi-raj-jain** [comment]
@ericallam Can I work on this one?

**Comment by rishi-raj-jain** [comment]
/attempt #186

@ericallam 

https://github.com/triggerdotdev/trigger.dev/issues/186#issuecomment-1642363658

What do you mean by that? Removing the secure option there? Or in the start command?

> docker build -f ./docker/Dockerfile -t <tag name here> .

What is this for?

**Comment by lalitkumawat1m** [comment]
Is this issue still open ? can I work on this issue?

**Comment by arika0093** [comment]
As stated in the above comment, the problem is essentially caused by the following factor: the Secure attribute of the cookie is enabled and cannot be loaded.

The question is why the above happens, and as far as I have been able to ascertain, it occurs when all of the following 1-3 conditions are met:

1. the connection is not HTTPS.  this is the expected case in localhost and self-hosting.
2. one of the following conditions is met. If either of the following conditions is true, secure cookies cannot be loaded.   
  * 2-1. the connection is not to `localhost` (for example, `127.0.0.1.nip.io`).
  * 2-2. your browser is safari.
3. the `Secure` attribute is set as a result of NODE_ENV = `production`. This can occur in either of the following.
  * 3-1. you have specified it as such in your `.env` file.
  * 3-2. you are booting from a docker image. This is because the startup command is fixed to `production` for convenience.

Now, of the above causes, only 3-2 can be handled on the code side (and I suspect it is the only one that can happen unintentionally). So I made a pull request for it.

If you have any conditions other than the above, I think you can work on that.

**Comment by nrhitik** [comment]
Can I still contribute and solve this issue or has this issue been solved?

**Comment by matt-aitken** [comment]
This issue is no longer relevant because when running the platform locally we now skip the email and just log you in.
