### ISSUE TITLE
[TRI-857] Record the setup experience and provide feedback

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#249]
We are looking for **10 people** to record themselves doing the setup experience of the product.

For each completed recording, we'll be giving a **$100 tip** using [Algora](https://console.algora.io/).

### Purpose

We are trying to make the initial experience better. That includes the CLI, in-app onboarding, and the quick start docs.

### Requirements

* You haven't used the product before.
* You do a continuous screen recording with your microphone turned on, ideally camera too but that's optional.
* Say aloud what you're thinking.

### What should go in the video

Try and do the following:

1. Create a Trigger.dev account: [https://cloud.trigger.dev](https://cloud.trigger.dev)
   1. Use the invite code: `continuous-delivery-862`
2. Go through the process of getting setup. Behave how you normally would trying to get it working.
3. Get the example Job running

If you get stuck or experience a bug, that's very useful. Don't cut this out of the video. Please share using the method below.

### Submission

Do not create a Pull Request.

1. Add a comment to this issue with the video attached.
2. (Optional but appreciated) Add any comments you have about how things could be better.
3. We will send you the £100 tip using Algora

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-857](https://linear.app/triggerdotdev/issue/TRI-857/record-the-setup-experience-and-provide-feedback)</sub>

**Comment by zodman** [comment]
First one! https://drive.google.com/file/d/1N4x7cSKnAn4SY4fIST3izCwZzxWuuF5u/view?usp=drive_link

other feedback it on the intervalTrigger I want to see when will be the next operation at least at the console.

```
the next execution will be at XX:XX XXX
```
Dont put `Coming soon`  and #250

**Comment by rishi-raj-jain** [comment]
I'm on it right now.

**Comment by rishi-raj-jain** [comment]
Mine!

- Part 1: https://drive.google.com/file/d/1RQ_AFtDQUrogtC7Hf5Ebg6ghZuCdB_Lb/view?usp=drive_link
- Part 2: https://drive.google.com/file/d/1eu_5xOmfZTTNP2VdP013TLb3Ypr5sPfw/view?usp=drive_link
(had to stop in between for a minute or two hence the two parts)

Feedback:

1. Make the homepage super crisp:
-- Cron's have a lot of configuration to see on the first view, just remove everything and put the required ones so that you can stress what's the benefit with minimal configuration
-- Similar feedback for events and webhooks

2. Event & Webhook both need to be educated to the customer:

- A webhook flow would be like say I'm going to Storyblok and adding an endpoint to POST to
-- In this case, how does the "webhook" case separate from "API endpoint"?

- In Event, What exactly is event? Like an event could be Storyblok hitting a POST endpoint because I made some changes in the CMS. What differentiates an event from webhook?

3. Improve the Next integration: As you could see in the video, it failed to detect my Next.js app! while it worked fine with the new app that I spun up next.

4. Highlight the difference between dev and production mode clearly: While I was clearly able to run the dev mode and test a job, I still searched docs, looked here and there to find that it was already on the dashboard suggesting me to use the Web console for the same. This needs a major improvement via CLI/NPM Package using the console to display the message and the mode the user is in.

**Comment by Anshul1811** [comment]
I also tried to run this and here is my video link .
https://drive.google.com/drive/folders/1G93DFR1IX3c5a1bJ9R-y4jilEGbzvxMv?usp=sharing
(There are 2 videos because in the 1st one my VS code setup is not visible so I tried to show it in the second part)


FEEDBACK:---
1.The docs and the steps mentioned are very helpful and useful.Whenever I got stuck there are steps available to guide through thats a nice thing to have.
2.I am able to successfully setup the job part in just span of few minutes despite being a begineer.So,I can say anyone can setup this easily it is purely begineer friendly.
3.So for me the overall experience was extremely good and I will definitely look forward to use these APIs in my future projects.

**Comment by RamK777-stack** [comment]
Hi, I have tried Trigger.dev for the first time today. here I am sharing my experiences.

[https://drive.google.com/drive/folders/18sRiRdjguhTPQZt-de6nDE9UsNtjEyUn](https://drive.google.com/drive/folders/18sRiRdjguhTPQZt-de6nDE9UsNtjEyUn) I uploaded as 3 parts because I am facing issues with node.js and next project in my machine.

Initially, during the onboarding process,  I am facing some design issues and validation issues. I think it's due to my screen size (13 inches). mentioned those in the above video.

other than that overall experience is good, since I am new to this. I don't understand what this tool is for and what triggers are, jobs, etc. 

Also, we can better improve this part in the readme section -> About Trigger.dev
Create long-running jobs directly in your codebase with features like API integrations, webhooks, scheduling and delays.

with the existing problem and how trigger.dev solving that problem, because as a new commer, not able to understand the need for this tool clearly.

Currently, I am reading the documentation, and I will definitely try this in my current project. 

Thanks.

**Comment by kaf-lamed-beyt** [comment]
I tried creating a Job by following the exact steps illustrated in the docs. I noticed some issues with the content in the doc that were not correlating. 

Like the one in the image below. It says I'll find the example job in the API routes folder, but it wasn't there, rather It was in the jobs folder inside `src` 

![Screenshot from 2023-08-03 09-24-54](https://github.com/triggerdotdev/trigger.dev/assets/48127194/870f0ac7-ff6f-4ff6-8186-8ac34271c463)

I also included some findings i made in the video.

Here's the link to the test with the `/pages` dir: [video](https://drive.google.com/file/d/1oeqcotwmB0tlib6nvsFCG7YcunVtCdfn/view?usp=sharing)

I'm carrying out another test with the `appDir`, when I'm done, I'll update it this comment with the link.

**Comment by yashug** [comment]
Hi, I completed a fresh setup of trigger.dev. The concept is cool, and I've provided a video walkthrough of the setup: [Link to Video](https://www.loom.com/share/4bfb6849e4184b62a0fda37be99f6b5f?sid=fc9b7965-f227-4f6c-965d-77281bfc4953)

**Feedback:**
During the setup, I encountered an issue while running the CLI init command. The problem was that the next app I created wasn't initialized with git using the git init command. It took me some time to debug this as it wasn't mentioned in the documentation as a required step for the next project. I was able to resolve it by checking the [CLI section](https://trigger.dev/docs/documentation/guides/cli) and focusing on the terminal animation, which said, "You have uncommitted git changes, you may want to commit them before continuing." This made me realize that git init for the next project is mandatory before running cli init.

**Other points:**
The rest of the process was smooth, and I was able to run the example trigger successfully.
Additionally, the guide should mention the creation of the "jobs" folder inside the app or pages directory, as it's not currently mentioned in the quick start guides. However, it is mentioned on the cloud dashboard.
Overall, I enjoyed the experience, and the product has great potential!

![Screenshot 2023-08-03 at 2 16 46 PM](https://github.com/triggerdotdev/trigger.dev/assets/14201280/a657167f-872d-43a8-b667-6616bd09bd84)

**Comment by jobenjada** [comment]
Love the idea of this, will steal it for Formbricks at some point 😄

**Comment by IMPranshu** [comment]
My recording is on the way. Thanks

**Comment by Roshan-Horo** [comment]
Hello all, I completed the setup with next.js ( quick start guide ), it was smooth setup because of the really good docs. 

Raw Video of the setup from start to finish ( 40 min ) : [Video Link]( https://drive.google.com/file/d/1ZliCbWLMQky788HxW_xS3XQWUA7SlUtq/view?usp=sharing)

Docs is really to the point, short and clear for most of the developers and beginner can also run it's first job.

I'm happy with the current state of the docs, but we can improve even better.

Feedback : 
- We can have different section for the `init` command - `Trigger.dev Cloud` and `Self-hosting` , for the Trigger.dev cloud , we got `init` command from dashboard which can add api key directly to .env file, and for the self-host we have to add it (which can be a small note )

**Comment by IMPranshu** [comment]
My setup video link on youtube https://youtu.be/fC3jdeZep8U

**Comment by pkdjne** [comment]
Just found out about this. Will give this a try.

**Comment by samejr** [comment]
> My setup video link on youtube https://youtu.be/fC3jdeZep8U

Hey can you try sending a google drive link or something other than YouTube? Youtube says your video is too long! 

(Im pretty sure Youtube max video length is 12 hours so this must be some epic feedback! 🤣)

**Comment by IMPranshu** [comment]
I am uploading the video in Gdrive @samejr. The video is of 25 min. I don't know if youtube is just not able to handle it I guess. I did manage to play with OpenAI though. It was fun :)

**Comment by samejr** [comment]
Amazing! Looking forward to watching it 👍

**Comment by IMPranshu** [comment]
Hey @samejr SD quality is up. 4K processing 120 mins remaining. Apologies!!!

**Comment by IMPranshu** [comment]
Yup. Will update you once 4k is done.

**Comment by IMPranshu** [comment]
4k upload done. Please do give feedback @samejr

**Comment by samejr** [comment]
Hi @IMPranshu just checked it out and it's great! Thanks so much.

**Comment by pkdjne** [comment]
I have tried the instructions. 
Some feedback : - I was using an older next js and the error thrown by the app CLI was I was not using Next.js app which i think is misleading instead it should tell that I am using an older version on next.js, that will help.

My video [link](https://drive.google.com/file/d/13Kr4cfm2mXPWW6y3TONQizmHi5bBhAbS/view?usp=sharing)

**Comment by shubhi2000** [comment]
I am on it right now. I believe I would be the 10th!

**Comment by abhishekmishragithub** [comment]
@matt-aitken First of all the project is really good, the idea of having a job framework for next js app is neat. (I come from Python background heavily and have used celery for most of my background job) 

### Regarding bounty :

I got the following error at the first step itself i.e. Initializing the trigger dev in a project with the following command:
```bash
npx @trigger.dev/cli@latest init -k tr_dev_ixxxxxx -t https://cloud.trigger.dev
```
- **Error:** `FetchError: request to https://api.trigger.dev/api/v1/whoami failed, reason: Socket connection timeout`

- **Screenshot:**
<img width="1015" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/38150419/67df5f25-5a70-49de-9baa-7d67fc28cf74">

- **Note:** The Next.js app is the sample app created using - `npx create-next-app@latest`
- **Video**: [uploading in progress]

**Comment by shubhi2000** [comment]
Hi,
Here is the link to my video: https://github.com/triggerdotdev/trigger.dev/assets/46618557/8feffdb0-9761-4488-a986-273065fbc5a3

This is the screenshot of the issue I faced:
![Screenshot from 2023-08-04 01-35-10](https://github.com/triggerdotdev/trigger.dev/assets/46618557/1f40cb76-997e-4ca5-aceb-bfcc51030c11)

Thanks!

**Comment by shubhi2000** [comment]
> I am on it right now. I believe I would be the 10th!

@samejr @ericallam I had added my work above. Please review and provide provide your feedback.

**Comment by samejr** [comment]
Thanks to everyone who contributed to this issue – your feedback has been really helpful 🙏

**Comment by abhishekmishragithub** [comment]
@matt-aitken or @samejr can you or someone help me with digging more with the error? or the cloud is still experimental? I wanted to explore more about how the jobs are done.

**Comment by samejr** [comment]
Hey @abhishekmishragithub im still going through some other videos but will get back to you when i've checked yours out properly.

**Comment by abhishekmishragithub** [comment]
> Hey @abhishekmishragithub im still going through some other videos but will get back to you when i've checked yours out properly.

Sure! Thanks.

**Comment by IMPranshu** [comment]
Hey @abhishekmishragithub which node version are you running?

**Comment by abhishekmishragithub** [comment]
> Hey @abhishekmishragithub which node version are you running?

v20.0.0

**Comment by IMPranshu** [comment]
Ok. One thing I have found is this error occurs when the CLI is not able to make a remote connection, which can be solved by using a different api key but in this case you might have to signup with a different account altogether. 
Can you try doing that once and see if it resolves the error?

**Comment by abhishekmishragithub** [comment]
> Ok. One thing I have found is this error occurs when the CLI is not able to make a remote connection, which can be solved by using a different api key but in this case you might have to signup with a different account altogether. Can you try doing that once and see if it resolves the error?

I will use different accounts and test. Will follow the approach mentioned in the docs. Thanks!

**Comment by IMPranshu** [comment]
Also try upgrading or downgrading node version. I am using `v20.3.1` and didn't face this issue but there are reports for other apps getting timeout error for `v20.0.0`

<img width="682" alt="Screenshot 2023-08-04 at 5 21 03 PM" src="https://github.com/triggerdotdev/trigger.dev/assets/43396684/fa5d228d-4551-499d-a3fc-8444b1a90dba">

see this https://github.com/npm/cli/issues/3078
