### ISSUE TITLE
[TRI-887] Tests for the CLI

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#263]
### Tests that

* The CLI init command succeeds or fails as appropriate
  * The project is correctly detected
  * The correct files have been created and configured correctly
  * The project builds, i.e. no syntax errors
* The CLI dev command succeeds or fails as appropriate

### Test situations

A separate public GitHub repo which has lots of directories in the root, each one is a project (just Next.js for now but soon Express etc). The first step in the e2e test would be to download the repo and then iterate through the folders.

* Different package managers
* Next.js App and pages directories
* Next.js 12 and 13

### Inspiration

[https://github.com/gmrchk/cli-testing-library](https://github.com/gmrchk/cli-testing-library)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-887](https://linear.app/triggerdotdev/issue/TRI-887/tests-for-the-cli)</sub>

**Comment by ologbonowiwi** [comment]
I would like to take a shot on this one.

**Comment by ologbonowiwi** [comment]
The first step to enable end-to-end tests would be setting up a test environment on the `cli` package.

I'll open a PR running a simple test (`expect(true).toBe(true)`), but ensuring that we're good in terms of configurations with Jest;
I'll do this to be sure that in upcoming test implementations, we'll need to care only about actual test assertions rather than getting everything working.

**Comment by ologbonowiwi** [comment]
#326 opened. I'm still familiarizing myself with `@gmrchk/cli-testing-library`, but from what I found so far, we'll probably need to run commands like on their examples `node ./my-cli something`, but we'll need to pass the next js project path as parameter to the CLI.

I left one example file doing this on the PR.

I hope it helps 😄

**Comment by ologbonowiwi** [comment]
> A separate public GitHub repo which has lots of directories in the root, each one is a project (just Next.js for now but soon Express etc). The first step in the e2e test would be to download the repo and then iterate through the folders.

One nice way we could do so would be by creating these projects where the CLI needs to fit, and we can iterate over them on the tests making the assertions. If you look [here](https://github.com/triggerdotdev/trigger.dev/pull/326/files#diff-0160ffc15207546cc8e2aca5c3a6f75b9b64f3a43959c94de95f90c6e6bdc2e1R18), you'll see that we have a NextJS path to pass to the commands. Instead of having one, we would iterate over all paths in `examples` files and run. The test suite multiple times, ensuring the same behavior over all projects.

Although it's a good approach, we need to account that this will take a ton of time to run. Maybe we could, in parallel, aim to have unit tests that would run fast and ensure at least the program behavior (and there's plenty of space to do so; we can, for example, assert that we're exporting the CLI commands, that we're calling the proper methods inside the CLI implementation, etc.).

I'm eager to contribute to the project and have some experience with automated testing. If you have anything that could be unit-tested in mind (not just in CLI but also in other packages inside the project), please raise the tickets, and I can try to implement some of the tests or at least create the test setups needed to execute those tests.

**Comment by matt-aitken** [comment]
Instead of e2e tests I've used `mock-fs` and created tests for each framework and separated everything into smaller chunks.
