### ISSUE TITLE
[TRI-1152] chore: upgrade webapp to use graphile-worker `0.14.0-rc.0`

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#396]
We're currently on 0.13.0 but `0.14.0` comes with automatic queue management, so it will be easier to do #392 along with other things:

* New "batch jobs" feature for merging payloads with a job_key (see README)
* Significantly improved 'large jobs table' performance (e.g. when a large queue is locked, or there's a lot of jobs queued for task identifiers your worker instance doesn't support, or a lot of failed jobs). Around 20x improvement in this 'worst case' performance for real user workloads.
* Added new (experimental) much faster add_jobs batch API.
* Fix error handling of cron issues in 'run' method.
* CronItem.match can now accept either a pattern string or a matcher function
* Jobs that were locked more than 4 hours will be reattempted as before, however they are slightly de-prioritised by virtue of having their run_at updated, giving interim jobs a chance to be executed (and lessening the impact of queue stalling through hanging tasks).

The full release notes are here:

[https://github.com/graphile/worker/blob/main/RELEASE_NOTES.md#v0140](https://github.com/graphile/worker/blob/main/RELEASE_NOTES.md#v0140)

As mentioned in the release notes, this is a breaking change, meaning workers running `0.13` cannot run against the `0.14` schema. So we'll need to make this clear in any release notes for this feature.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1152](https://linear.app/triggerdotdev/issue/TRI-1152/chore-upgrade-webapp-to-use-graphile-worker-0140-rc0)</sub>

**Comment by nicktrn** [comment]
Just ticking some boxes to know what needs actioning.

### Breaking changes

- [x] Bump minimum Node version to 14
- [x] Bump minimum PG version to 12
- [x] `priority`, `attempts` and `max_attempts` are now `smallint`, i.e. values have to be between `-32768` and `32768`
  * Using current max of `100`
- [ ] `CronItem.pattern` has been renamed to `CronItem.match`
  * TODO: Rename this in recurring tasks and `ZodWorker` 
- [x] Database error codes have been removed because we've moved to CHECK constraints
  * We don't rely on specific error codes

### Internal changes

- [x] The 'jobs' table no longer has `queue_name` and `task_identifier` columns
  * We don't rely on specific column names (see below for raw query returns)
- [x] Internal SQL functions (`get_job`, `fail_job`, `complete_job`) have been moved to JS
- [x] Most triggers removed, could cause problems if directly inserting into jobs table
  * We don't do this

### Migration

- [ ] Will NOT run if there are any locked jobs - read: `locked_at` in last 4 hours
  * TODO: Graceful shutdown should usually take care of this. May want to provide a simple script to clear all locks.
- [x] Ensure the `jobs` table is not referenced directly in a custom function
  * We don't do this (yet)

### Raw queries

- [x] Ensure SQL function signatures still match
  * Integer types were only changed internally
- [ ] Ensure SQL function returns still match
  * TODO: Check `GraphileJobSchema`, particularly `queue_name` and `task_identifier`

## Summary

Seems a smooth migration will come down to three things:

1. Ensuring no jobs are currently locked, possibly creating an "unlock" script
2. Renaming `CronItem.pattern` to `CronItem.match`
3. Adjusting parsers for SQL function call returns
