### ISSUE TITLE
[TRI-1168] When indexing Jobs, if they fail to parse the errors don't get sent back to users

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#420]
To reproduce create a Job with an interval of less than 60 seconds, and reun `npx @trigger.dev/cli@latest dev`

```
client.defineJob({
  // This is the unique identifier for your Job, it must be unique across all Jobs in your project
  id: "job-3",
  name: "Third job",
  version: "0.0.3",
  // This is triggered by an event using eventTrigger. You can also trigger Jobs with webhooks, on schedules, and more: https://trigger.dev/docs/documentation/concepts/triggers/introduction
  trigger: intervalTrigger({
    seconds: 5,
  }),
  run: async (payload, io, ctx) => {
    await io.logger.info("You console it! 🤦");
  },
});
```

This will silently fail to appear in the dashboard and will stop all other Jobs from registering as well.

We need to change this code to use safeParse and to return an error with the details if it fails.

[https://github.com/triggerdotdev/trigger.dev/blob/1d7e5737a0234b5654a685b08f5c09720018fbb9/apps/webapp/app/services/endpointApi.server.ts#L131](https://github.com/triggerdotdev/trigger.dev/blob/1d7e5737a0234b5654a685b08f5c09720018fbb9/apps/webapp/app/services/endpointApi.server.ts#L131)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1168](https://linear.app/triggerdotdev/issue/TRI-1168/when-indexing-jobs-if-they-fail-to-parse-the-errors-dont-get-sent-back)</sub>

**Comment by ericallam** [comment]
This isn't as easy as it sounds, because indexing an endpoint occurs in a background graphile worker task, and wouldn't make sense in the context of indexing production endpoints. We should probably surface the error in the dashboard in some way instead, and maybe an email as well (especially for production endpoints). We should also make it so this doesn't actually cause a parse issue. Another thing we could do is have the dev command poll an API endpoint with the EndpointIndex ID and that would give back information about what happened in the indexing and if there were any errors, that way the error would display in the CLI.

**Comment by matt-aitken** [comment]
This is a duplicate of #514
