### ISSUE TITLE
[TRI-1355] bug: Requests to endpoints that respond with redirects are considering failing

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#543]
### Provide environment information

  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 101.13 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 7.18.1 - ~/.nvm/versions/node/v18.12.1/bin/pnpm

### Describe the bug

When the server makes requests to endpoints and the endpoint responds with a redirect, the request is considered a failure. This causes issues with indexing endpoints, executing runs, and delivering webhook payloads. So basically nothing works if the endpoint responds with a redirect. For example, if the endpoint url was input as something like `"https://foo.com/api/trigger"` and when making a request to the endpoint the response is a 308 redirect to`"https://www.foo.com/api/trigger"`.

### Reproduction repo

N/A

### To reproduce

Setup a new Next.js project with a Trigger.dev integration, and setup an endpoint that will redirect to the actual `/api/trigger` endpoint. 

<sub>[TRI-1355](https://linear.app/triggerdotdev/issue/TRI-1355/bug-requests-to-endpoints-that-respond-with-redirects-are-considering)</sub>

**Comment by hmacr** [comment]
@ericallam
I set up an endpoint `/api/redirect` which responds with a redirect to `/api/trigger`. Then I updated the endpoint URL in the dashboard to the new endpoint.
The trigger server was able to follow the redirect and index the endpoints.

Additionally, I logged the `response.redirected` property to verify the behaviour.
![Screenshot 2023-10-05 at 3 29 20 PM](https://github.com/triggerdotdev/trigger.dev/assets/132386067/bfd2988d-c41d-49c8-8a48-26eb7d63dedf)

I'm not sure what the intention of the bug here is. Maybe I misunderstood it?

**Comment by ericallam** [comment]
Interesting that worked! Can you try making it a 308 redirect?

**Comment by hmacr** [comment]
That works too! Was this bug something that you stumbled upon?

**Comment by ericallam** [comment]
Yea it was a user on our cloud and they had an endpoint URL `https://foo.com/api/trigger` that was responding with a 308 redirect to `https://www.foo.com/api/trigger`. Once I updated the endpoint URL to `https://www.foo.com/api/trigger` it started working. Very strange.

**Comment by matt-aitken** [comment]
@ericallam fixed this
