### ISSUE TITLE
bug: Environment & Status pickers don't work for a single job view

### ISSUE THREAD

**Issue by ky-zo** [triggerdotdev/trigger.dev#966]
### Provide environment information

macOS 13.6.1 (22G313)
Arc Version 1.35.0 (47750)
Chromium Engine Version 123.0.6312.59

### Describe the bug

It's not possible to filter job runs based on the environment or status. When clicking on the filtering element, website throws an error to the console.

<img width="543" alt="Screenshot 2024-03-24 at 18 07 01" src="https://github.com/triggerdotdev/trigger.dev/assets/30871809/60fb9719-0a83-4867-99be-e20d2745bca8">

### Reproduction repo

N/A

### To reproduce

Open cloud.trigger.dev, go to Jobs list and open a single job. Try to filter Environment or Status.

**Comment by matt-aitken** [comment]
@ky-zo I'm struggling to reproduce this using:
Arc Version 1.35.0 (47750)
Chromium Engine Version 123.0.6312.59
Mac OS 14.4 (23E214)

https://github.com/triggerdotdev/trigger.dev/assets/10635986/3c67c09a-fea6-4a51-ad8c-cee30f3de11c

I'm wondering if this is a Chrome extension issue, they break a lot of React server-side rendered sites because they inject stuff into the <head>.

**Comment by ky-zo** [comment]
I think it might have been extension issue. It works fine today 🫠

Sorry for wasting your time.

**Comment by matt-aitken** [comment]
@ky-zo no problem! I'd rather we check everything is working properly 😃
